//GET /Progress: 
GET http://localhost:5000/users/progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcwNTYyOCwiZXhwIjoxNzM2NzA5MjI4fQ.zTXQjsRKPY7U5cJCZ1gusR5ou1PbxvRDV9kSZqUDv0U

### Quizfragen Englisch testen 
GET http://localhost:5000/users/quiz/english
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcwNTYyOCwiZXhwIjoxNzM2NzA5MjI4fQ.zTXQjsRKPY7U5cJCZ1gusR5ou1PbxvRDV9kSZqUDv0U

### Quizfragen Englisch testen 
GET http://localhost:5000/users/quiz/math
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcwNTYyOCwiZXhwIjoxNzM2NzA5MjI4fQ.zTXQjsRKPY7U5cJCZ1gusR5ou1PbxvRDV9kSZqUDv0U


### Fortschritt überprüfen
GET http://localhost:5000/users/progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcwNTYyOCwiZXhwIjoxNzM2NzA5MjI4fQ.zTXQjsRKPY7U5cJCZ1gusR5ou1PbxvRDV9kSZqUDv0U



### Ranglisten überprüfen
GET http://localhost:5000/users/leaderboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcxODQ1MSwiZXhwIjoxNzM2NzIyMDUxfQ.osvBPw6XFMirLGxmTgXpgGzuQMq_ZaHRoU7lTmtujdc

### Ranglisten mit Kategorie "math" abrufen
GET http://localhost:5000/users/leaderboard/math
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcyMTYzNCwiZXhwIjoxNzM2NzI1MjM0fQ.3bY9lYaGII2p_kF3KS0ho1Xa7Gg7J5slT4uE4-H-fPg

### Ranglisten mit Kategorie "english" abrufen
GET http://localhost:5000/users/leaderboard/english
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcyMTYzNCwiZXhwIjoxNzM2NzI1MjM0fQ.3bY9lYaGII2p_kF3KS0ho1Xa7Gg7J5slT4uE4-H-fPg

### Gesamtrangliste abrufen
GET http://localhost:5000/users/leaderboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcyMTYzNCwiZXhwIjoxNzM2NzI1MjM0fQ.3bY9lYaGII2p_kF3KS0ho1Xa7Gg7J5slT4uE4-H-fPg

### Paginierungslogik für alle Kategorie 
GET /users/leaderboard?page=1&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcyNzU2MSwiZXhwIjoxNzM2NzMxMTYxfQ._HywzYw4l6AIjVpQ-DZhrZHK_32ntxaljwlFUkdA75Y

### Paginierungslogik für Kategorie math 
GET /users/leaderboard/math?page=2&limit=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjcyNzQxMSwiZXhwIjoxNzM2NzMxMDExfQ.2SH70gaSXUyuoIz-bFXvLIMoGUb6RFaWzED5LiDCd0A

### Paginierung mit Suche 
GET /users/leaderboard?page=1&limit=5&search=John
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjc5OTY0MCwiZXhwIjoxNzM2ODAzMjQwfQ.DT8qp6aksdEpuGGQ6LoaYXwjJ01HlZPwoMvfL5xm_A4


###POST /progress (Fortschritt speichern)
POST http://localhost:5000/users/progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjY5NTc5MiwiZXhwIjoxNzM2Njk5MzkyfQ.yA74Mx8qgoq-L0BToRarWLQxmSAowEJOKpWBgOyXSpg
{
  "category": "math",
  "score": 8
}

### GET /profile (Benutzerprofil anzeigen)
GET http://localhost:5000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjYzNTEzOSwiZXhwIjoxNzM2NjM4NzM5fQ.q9aOTpmD9bnVrxUsSpIEqYM3kVZN2u9P2d_SjX_NJPs


### Test 1: Score = 3 (Bronzemedaille)
POST http://localhost:5000/users/progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjYzMzAxNCwiZXhwIjoxNzM2NjM2NjE0fQ.zZAfq_yuzGvcZP1yhz600YU4tqz3KLxQPPpqk3NEkD0

{
  "category": "math",
  "score": 3
}

### Test 2: Score = 5 (Silbermedaille)
POST http://localhost:5000/users/progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjYzMzAxNCwiZXhwIjoxNzM2NjM2NjE0fQ.zZAfq_yuzGvcZP1yhz600YU4tqz3KLxQPPpqk3NEkD0


{
  "category": "math",
  "score": 5
}

### Test 3: Score = 10 (Goldmedaille)
POST http://localhost:5000/users/progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjYzMzAxNCwiZXhwIjoxNzM2NjM2NjE0fQ.zZAfq_yuzGvcZP1yhz600YU4tqz3KLxQPPpqk3NEkD0

{
  "category": "math",
  "score": 10
}


### Token-Refresh testen
POST http://localhost:5000/users/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNjYzMzAxNCwiZXhwIjoxNzM2NjM2NjE0fQ.zZAfq_yuzGvcZP1yhz600YU4tqz3KLxQPPpqk3NEkD0

