//GET /Progress: 
GET http://localhost:5000/users/progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJiYWRhMTIzNCIsImlhdCI6MTczOTgzNDAyOSwiZXhwIjoxNzM5ODM3NjI5fQ.zXVSO8v-JdLiGQITi_pj2kAGG8_puDgGPm9IVYkXy6E

### Quizfragen Englisch testen 
GET http://localhost:5000/users/quiz/english
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJiYWRhMTIzNCIsImlhdCI6MTczOTgzNDAyOSwiZXhwIjoxNzM5ODM3NjI5fQ.zXVSO8v-JdLiGQITi_pj2kAGG8_puDgGPm9IVYkXy6E


### Quizfragen math testen 
GET http://localhost:5000/users/quiz/math
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjE3NCwiZXhwIjoxNzM3MTM1Nzc0fQ._JJssQ7L6m-PKY8LnNvyceeWOc8QCdBkDpyoxsTy3Lo


### Fortschritt überprüfen
GET http://localhost:5000/users/progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjE3NCwiZXhwIjoxNzM3MTM1Nzc0fQ._JJssQ7L6m-PKY8LnNvyceeWOc8QCdBkDpyoxsTy3Lo

### Progresspage Testen
GET http://localhost:5000/users/progress -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywidXNlcm5hbWUiOiJoYWRhMTIzNCIsImlhdCI6MTczOTkxNDA4MywiZXhwIjoxNzM5OTE3NjgzfQ.TThgL_OhEcGq2xjVDnDCVp5X8lTz7UX5VOkrz5SDM1M"



### Ranglisten überprüfen
GET http://localhost:5000/users/leaderboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjE3NCwiZXhwIjoxNzM3MTM1Nzc0fQ._JJssQ7L6m-PKY8LnNvyceeWOc8QCdBkDpyoxsTy3Lo

### Ranglisten mit Kategorie "math" abrufen
GET http://localhost:5000/users/leaderboard/math
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjE3NCwiZXhwIjoxNzM3MTM1Nzc0fQ._JJssQ7L6m-PKY8LnNvyceeWOc8QCdBkDpyoxsTy3Lo

### Ranglisten mit Kategorie "english" abrufen
GET http://localhost:5000/users/leaderboard/english
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjE3NCwiZXhwIjoxNzM3MTM1Nzc0fQ._JJssQ7L6m-PKY8LnNvyceeWOc8QCdBkDpyoxsTy3Lo

### Gesamtrangliste abrufen
GET http://localhost:5000/users/leaderboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjE3NCwiZXhwIjoxNzM3MTM1Nzc0fQ._JJssQ7L6m-PKY8LnNvyceeWOc8QCdBkDpyoxsTy3Lo


### GET /profile (Benutzerprofil anzeigen)
GET http://localhost:5000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjQ1NCwiZXhwIjoxNzM3MTM2MDU0fQ.szfYpg2GWJylixtfTkDhz95-f59KTwco_touORbpwe8


### Test 1: Score = 3 (Bronzemedaille)
POST http://localhost:5000/users/progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjQ1NCwiZXhwIjoxNzM3MTM2MDU0fQ.szfYpg2GWJylixtfTkDhz95-f59KTwco_touORbpwe8

{
  "category": "math",
  "score": 3
}

### Test 2: Score = 5 (Silbermedaille)
POST http://localhost:5000/users/progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjQ1NCwiZXhwIjoxNzM3MTM2MDU0fQ.szfYpg2GWJylixtfTkDhz95-f59KTwco_touORbpwe8


{
  "category": "math",
  "score": 5
}

### Test 3: Score = 10 (Goldmedaille)
POST http://localhost:5000/users/progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTczNzEzMjQ1NCwiZXhwIjoxNzM3MTM2MDU0fQ.szfYpg2GWJylixtfTkDhz95-f59KTwco_touORbpwe8

{
  "category": "math",
  "score": 10
}



